[package]
name = "Space-Travel"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.1"
nalgebra-glm = "0.19.0"
minifb = "0.27.0"
fastnoise-lite = "1.1.1"
tobj = "4.0.2"
rand = "0.8" 
image = "0.25.5" # Verifica la última versión en crates.io
